aiephys/multipatch_analysis

connectivity_summary.py, constants.py, experiment.py, experiment_list.py
Compile completed stim-sets per connection type
=> Stim set summary

experiment_list.py
Wasn't grabbing quads in the case that you were looking for a like-to-like connection
=> fix cre-type parser

synapse_comparison.py
add analysis of 50Hz train responses to `synapse_comparison`. This is passed as an optional argument `--trains` as they are not cached and it is fairly slow.
=> Train responses

connection_detection.py, figure_1.py
small fixes to figure 1 code and fix to `connection_detection` to use UID
=> Manuscript figures

multipatch_analysis/experiment_list.py
....still need to work out Total Connection count
=> update reciprocal_summary types to match summary_types

multipatch_analysis/experiment_list.py, tools/connectivity_summary.py
Also added plotting for human and mouse E-E connectivity
=> Update layer/cre type access for distance analysis

multipatch_analysis/database/database.py
=> sqlalchemy version control, deleted __main__

analyses/first_pulse_feature.py, tools/specimen_to_expt.py
=> Type switch

analyses/manuscript_figures.py
Please merge these comments (no code changes).
=> adding commenting to manuscript_figures.py

tools/dashboard.py
=> fixes to dashboard

tools/dashboard.py
- check all file paths for rig name and pipette.yml file 
- reorder expt flow, submitted before data
=> updates to dashboard: 

util/metadata_cleanup.py
- dissection time
- acsf
- internal
- project code
- target region
- rig name
=> hopefully complete metadata checks:

multipatch_analysis/constants.py, multipatch_analysis/metadata_submission.py
- Added PatchSeq to internal constants
- pip['pipette_status'] != pip['status']
=> Submission fixes

multipatch_analysis/metadata_submission.py
- increase dissection time diff to 10 hrs
- add '?' to acceptable label marker
=> updates to submission

analyses/first_pulse_feature.py, analyses/manuscript_figures.py, analyses/tests/save_fit_psp_test_set.py, analyses/tests/test_psp_fitting.py, multipatch_analysis/connection_detection.py, multipatch_analysis/synaptic_dynamics.py
This version includes tests not yet migrated to neuroanalysis.  However the test data has been deleted from the history.  I still did not figure out how to access the data in the submodule so the path is currently hard coded.  Please suggest the fix or just merge.
=> Psp fitting fix branch

analyses/connectivity.py, analyses/lee_pvalb_distance.py, analyses/manuscript_fig_4.py, analyses/manuscript_figures.py, analyses/strength_analysis.py, multipatch_analysis/cell_class.py, multipatch_analysis/connection_strength.py, multipatch_analysis/connectivity.py, multipatch_analysis/database/database.py, multipatch_analysis/experiment.py, multipatch_analysis/experiment_list.py, multipatch_analysis/lims.py, multipatch_analysis/metadata_submission.py, multipatch_analysis/ui/graphics.py, tools/connectivity_summary.py
Many changes introduced to support use of database to generate MS figure 4:
* Added cell_class.py, which is used to represent cell classes and determine whether a cell is a member of a class
* Added connectivity.py, which is used for measuring connectivity between cell classes
* Minor DB structural change `experiment.pairs` is now a dict `{(pre, post):Pair}`
* Numerous changes that reduce data graveyard attrition
=> manuscript databse updates

multipatch_analysis/ui/acq4_modules.py
Creates cell specimens without 20x image
Doesn't disrupt cell mapping as originally intended
=> edit cell_mapping to not require a 20x image 

multipatch_analysis/ui/dashboard.py
look for mpe_ignore file, if there print the message for further action
=> add more information about LIMS upload status

analyses/connectivity.py
the beginning of making our matrix interactive
=> add project filter to matrix

analyses/connectivity.py, multipatch_analysis/connectivity.py
Mouse Cell Class filter by layer
Calculate total matrix progress
Expanded printed info on element click
=> added features

analyses/connectivity.py, multipatch_analysis/connectivity.py, multipatch_analysis/database/__init__.py, multipatch_analysis/database/dynamics.py, multipatch_analysis/pipeline/__init__.py, multipatch_analysis/pipeline/dynamics.py
plus scatter plot added to histogram when element clicked
=> Dynamics Analyzer!

multipatch_analysis/fit_average_first_pulse.py, multipatch_analysis/pipeline/first_pulse_fit.py
Please merge so that fitting fails smoothly:)
=> adding known errors

multipatch_analysis/database/__init__.py, multipatch_analysis/database/gap_junction.py, multipatch_analysis/pipeline/gap_junction.py
=> Gap junction

multipatch_analysis/database/first_pulse_fit.py, multipatch_analysis/fit_average_first_pulse.py, multipatch_analysis/pipeline/__init__.py, multipatch_analysis/pipeline/first_pulse_fit.py, multipatch_analysis/test_fit_single_first_pulse.py
Single and average tables are still coupled here.
=> Single pulse fit

multipatch_analysis/matrix_analyzer/analyzers.py
explicitly set dtypes for group_results
=> matrix_analyzer bugfix 

multipatch_analysis/ui/acq4_modules.py
....users will set manually in LIMS
=> remove cell_map_no_go from acq_4 modules

tools/pair_analysis.py
link all user latency lines
allow user to type in latency to set line position
"Fit Responses" button to initiate fits (with 1ms initial latency)
logic for reloading pairs in which initial latencies differed across modes
=> Latency line

multipatch_analysis/database/experiment.py, multipatch_analysis/database/pipeline.py, multipatch_analysis/pipeline/pipeline_module.py
Changes to the database structure for 2p opto data:
-added ext_id field to experiment
-changed cell.ext_id and electrode.ext_id from int to str
-changed job_id to be a str instead of a float
=> Opto db changes
